name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            cd /root/Dialian

            git pull

            source venv/bin/activate

            export TOKEN="${{ secrets.TOKEN }}"

            nohup python3 dial.py > bot.log 2>&1 < /dev/null &
